/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Users {
  created_at: number;
  email: string;
  id: string | null;
}

export interface DB {
  users: Users;
}
