/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Contacts {
  createdAt: number;
  doubleOptInConfirmed: number | null;
  doubleOptInSent: number | null;
  doubleOptInToken: string;
  email: string;
  id: string | null;
}

export interface Sparks {
  last: number;
  nr: Generated<number>;
}

export interface DB {
  contacts: Contacts;
  sparks: Sparks;
}
