/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Users {
  createdAt: number;
  email: string;
  id: string | null;
}

export interface DB {
  users: Users;
}
